
from covid19_capstone.utils.snowflake_configuration import get_snowflake_engine
from sqlalchemy import text

def create_bronze_ods_tables():
    engine = get_snowflake_engine(schema='BRONZE')


    create_sql = """
    CREATE OR REPLACE TABLE BRONZE.ODS_GLOBAL_DAILY_DATA (
        Date_reported DATE,
        Country_code VARCHAR,
        Country VARCHAR,
        WHO_region VARCHAR,
        New_cases NUMBER,
        Cumulative_cases NUMBER,
        New_deaths NUMBER,
        Cumulative_deaths NUMBER,
        business_date DATE DEFAULT CURRENT_DATE
    );

    CREATE OR REPLACE TABLE BRONZE.ODS_GLOBAL_DATA (
        Date_reported DATE,
        Country_code VARCHAR,
        Country VARCHAR,
        WHO_region VARCHAR,
        New_cases NUMBER,
        Cumulative_cases NUMBER,
        New_deaths NUMBER,
        Cumulative_deaths NUMBER,
        business_date DATE DEFAULT CURRENT_DATE
    );

    CREATE OR REPLACE TABLE BRONZE.ODS_GLOBAL_TABLE_DATA (
        Name VARCHAR,
        WHO_Region VARCHAR,
        Cases_cumulative_total NUMBER,
        Cases_cumulative_total_per_100k NUMBER,
        Cases_last_7_days NUMBER,
        Cases_last_7_days_per_100k NUMBER,
        Cases_last_24_hours NUMBER,
        Deaths_cumulative_total NUMBER,
        Deaths_cumulative_total_per_100k NUMBER,
        Deaths_last_7_days NUMBER,
        Deaths_last_7_days_per_100k NUMBER,
        Deaths_last_24_hours NUMBER,
        business_date DATE DEFAULT CURRENT_DATE
    );

    CREATE OR REPLACE TABLE BRONZE.ODS_MONTHLY_DEATH_BY_AGE (
        Country VARCHAR,
        Country_code VARCHAR,
        Who_region VARCHAR,
        Wb_income VARCHAR,
        Year NUMBER,
        Month NUMBER,
        Agegroup VARCHAR,
        Deaths NUMBER,
        business_date DATE DEFAULT CURRENT_DATE
    );

    CREATE OR REPLACE TABLE BRONZE.ODS_HOSP_ICU_DATA (
        Date_reported DATE,
        Country_code VARCHAR,
        Country VARCHAR,
        WHO_region VARCHAR,
        Covid_new_hospitalizations_last_7days NUMBER,
        Covid_new_icu_admissions_last_7days NUMBER,
        Covid_new_hospitalizations_last_28days NUMBER,
        Covid_new_icu_admissions_last_28days NUMBER,
        business_date DATE DEFAULT CURRENT_DATE
    );

    CREATE OR REPLACE TABLE BRONZE.ODS_VACCINATION_DATA (
        COUNTRY VARCHAR,
        ISO3 VARCHAR,
        WHO_REGION VARCHAR,
        DATA_SOURCE VARCHAR,
        DATE_UPDATED DATE,
        TOTAL_VACCINATIONS NUMBER,
        PERSONS_VACCINATED_1PLUS_DOSE NUMBER,
        TOTAL_VACCINATIONS_PER100 NUMBER,
        PERSONS_VACCINATED_1PLUS_DOSE_PER100 NUMBER,
        PERSONS_LAST_DOSE NUMBER,
        PERSONS_LAST_DOSE_PER100 NUMBER,
        VACCINES_USED VARCHAR,
        FIRST_VACCINE_DATE DATE,
        NUMBER_VACCINES_TYPES_USED NUMBER,
        PERSONS_BOOSTER_ADD_DOSE NUMBER,
        PERSONS_BOOSTER_ADD_DOSE_PER100 NUMBER,
        business_date DATE DEFAULT CURRENT_DATE
    );

    CREATE OR REPLACE TABLE BRONZE.ODS_COVID_STATE_HISTORY (
        "DATE" DATE,
        STATE VARCHAR,
        DEATH INT,
        DEATH_CONFIRMED INT,
        DEATH_INCREASE INT,
        DEATH_PROBABLE INT,
        HOSPITALIZED INT,
        HOSPITALIZED_CUMULATIVE INT,
        HOSPITALIZED_CURRENTLY INT,
        HOSPITALIZED_INCREASE INT,
        IN_ICU_CUMULATIVE INT,
        IN_ICU_CURRENTLY INT,
        NEGATIVE INT,
        NEGATIVE_INCREASE INT,
        NEGATIVE_TESTS_ANTIBODY INT,
        NEGATIVE_TESTS_PEOPLE_ANTIBODY INT,
        NEGATIVE_TESTS_VIRAL INT,
        ON_VENTILATOR_CUMULATIVE INT,
        ON_VENTILATOR_CURRENTLY INT,
        POSITIVE INT,
        POSITIVE_CASES_VIRAL INT,
        POSITIVE_INCREASE INT,
        POSITIVE_SCORE INT,
        POSITIVE_TESTS_ANTIBODY INT,
        POSITIVE_TESTS_ANTIGEN INT,
        POSITIVE_TESTS_PEOPLE_ANTIBODY INT,
        POSITIVE_TESTS_PEOPLE_ANTIGEN INT,
        POSITIVE_TESTS_VIRAL INT,
        RECOVERED INT,
        TOTAL_TEST_ENCOUNTERS_VIRAL INT,
        TOTAL_TEST_ENCOUNTERS_VIRAL_INCREASE INT,
        TOTAL_TEST_RESULTS INT,
        TOTAL_TEST_RESULTS_INCREASE INT,
        TOTAL_TESTS_ANTIBODY INT,
        TOTAL_TESTS_ANTIGEN INT,
        TOTAL_TESTS_PEOPLE_ANTIBODY INT,
        TOTAL_TESTS_PEOPLE_ANTIGEN INT,
        TOTAL_TESTS_PEOPLE_VIRAL INT,
        TOTAL_TESTS_PEOPLE_VIRAL_INCREASE INT,
        TOTAL_TESTS_VIRAL INT,
        TOTAL_TESTS_VIRAL_INCREASE INT,
        BUSINESS_DATE DATE DEFAULT CURRENT_DATE
    );


    -- Synthetic Patient Data

    -- ODS_ENCOUNTERS
    CREATE OR REPLACE TABLE BRONZE.ODS_ENCOUNTERS (
        ID VARCHAR,
        "START" TIMESTAMP_TZ,
        "STOP" TIMESTAMP_TZ,
        PATIENT VARCHAR,
        ORGANIZATION VARCHAR,
        PROVIDER VARCHAR,
        PAYER VARCHAR,
        ENCOUNTERCLASS VARCHAR,
        CODE VARCHAR,
        DESCRIPTION VARCHAR,
        BASE_ENCOUNTER_COST FLOAT,
        TOTAL_CLAIM_COST FLOAT,
        PAYER_COVERAGE FLOAT,
        REASONCODE VARCHAR,
        REASONDESCRIPTION VARCHAR,
        BUSINESS_DATE DATE DEFAULT CURRENT_DATE

    );

    -- ODS_IMMUNIZATIONS
    CREATE OR REPLACE TABLE BRONZE.ODS_IMMUNIZATIONS (
        "DATE" DATE,
        PATIENT VARCHAR,
        ENCOUNTER VARCHAR,
        CODE VARCHAR,
        DESCRIPTION VARCHAR,
        BASE_COST FLOAT,
        BUSINESS_DATE DATE DEFAULT CURRENT_DATE
    );

    -- ODS_PATIENTS
    CREATE OR REPLACE TABLE BRONZE.ODS_PATIENTS (
        ID VARCHAR,
        BIRTHDATE DATE,
        DEATHDATE DATE,
        SSN VARCHAR,
        DRIVERS VARCHAR,
        PASSPORT VARCHAR,
        PREFIX VARCHAR,
        FIRST VARCHAR,
        LAST VARCHAR,
        SUFFIX VARCHAR,
        MAIDEN VARCHAR,
        MARITAL VARCHAR,
        RACE VARCHAR,
        ETHNICITY VARCHAR,
        GENDER VARCHAR,
        BIRTHPLACE VARCHAR,
        ADDRESS VARCHAR,
        CITY VARCHAR,
        STATE VARCHAR,
        COUNTY VARCHAR,
        ZIP VARCHAR,
        LAT FLOAT,
        LON FLOAT,
        HEALTHCARE_EXPENSES FLOAT,
        HEALTHCARE_COVERAGE FLOAT,
        BUSINESS_DATE DATE DEFAULT CURRENT_DATE
    );

    -- ODS_ALLERGIES
    CREATE OR REPLACE TABLE BRONZE.ODS_ALLERGIES (
        "START" DATE,
        "STOP" DATE,
        PATIENT VARCHAR,
        ENCOUNTER VARCHAR,
        CODE VARCHAR,
        DESCRIPTION VARCHAR,
        BUSINESS_DATE DATE DEFAULT CURRENT_DATE
    );

    -- ODS_CAREPLANS
    CREATE OR REPLACE TABLE BRONZE.ODS_CAREPLANS (
        ID VARCHAR,
        "START" DATE,
        "STOP" DATE,
        PATIENT VARCHAR,
        ENCOUNTER VARCHAR,
        CODE VARCHAR,
        DESCRIPTION VARCHAR,
        REASONCODE VARCHAR,
        REASONDESCRIPTION VARCHAR,
        BUSINESS_DATE DATE DEFAULT CURRENT_DATE
    );

    -- ODS_CONDITIONS
    CREATE OR REPLACE TABLE BRONZE.ODS_CONDITIONS (
        "START" DATE,
        "STOP" DATE,
        PATIENT VARCHAR,
        ENCOUNTER VARCHAR,
        CODE VARCHAR,
        DESCRIPTION VARCHAR,
        BUSINESS_DATE DATE DEFAULT CURRENT_DATE
    );

    -- ODS_ORGANIZATIONS
    CREATE OR REPLACE TABLE BRONZE.ODS_ORGANIZATIONS (
        ID VARCHAR,
        NAME VARCHAR,
        ADDRESS VARCHAR,
        CITY VARCHAR,
        STATE VARCHAR,
        ZIP VARCHAR,
        LAT FLOAT,
        LON FLOAT,
        PHONE VARCHAR,
        REVENUE FLOAT,
        UTILIZATION FLOAT,
        BUSINESS_DATE DATE DEFAULT CURRENT_DATE
    );

    -- ODS_PROCEDURES
    CREATE OR REPLACE TABLE BRONZE.ODS_PROCEDURES (
        "DATE" DATE,
        PATIENT VARCHAR,
        ENCOUNTER VARCHAR,
        CODE VARCHAR,
        DESCRIPTION VARCHAR,
        BASE_COST FLOAT,
        REASONCODE VARCHAR,
        REASONDESCRIPTION VARCHAR,
        BUSINESS_DATE DATE DEFAULT CURRENT_DATE
    );

    -- ODS_IMAGING_STUDIES
    CREATE OR REPLACE TABLE BRONZE.ODS_IMAGING_STUDIES (
        ID VARCHAR,
        "DATE" DATE,
        PATIENT VARCHAR,
        ENCOUNTER VARCHAR,
        BODYSITE_CODE VARCHAR,
        BODYSITE_DESCRIPTION VARCHAR,
        MODALITY_CODE VARCHAR,
        MODALITY_DESCRIPTION VARCHAR,
        SOP_CODE VARCHAR,
        SOP_DESCRIPTION VARCHAR,
        BUSINESS_DATE DATE DEFAULT CURRENT_DATE
    );

    -- ODS_MEDICATIONS
    CREATE OR REPLACE TABLE BRONZE.ODS_MEDICATIONS (
        "START" DATE,
        "STOP" DATE,
        PATIENT VARCHAR,
        PAYER VARCHAR,
        ENCOUNTER VARCHAR,
        CODE VARCHAR,
        DESCRIPTION VARCHAR,
        BASE_COST FLOAT,
        PAYER_COVERAGE FLOAT,
        DISPENSES INT,
        TOTALCOST FLOAT,
        REASONCODE VARCHAR,
        REASONDESCRIPTION VARCHAR,
        BUSINESS_DATE DATE DEFAULT CURRENT_DATE
    );

    -- ODS_PAYER_TRANSITIONS
    CREATE OR REPLACE TABLE BRONZE.ODS_PAYER_TRANSITIONS (
        PATIENT VARCHAR,
        START_YEAR INT,
        END_YEAR INT,
        PAYER VARCHAR,
        OWNERSHIP VARCHAR,
        BUSINESS_DATE DATE DEFAULT CURRENT_DATE
    );

    CREATE OR REPLACE TABLE BRONZE.ODS_PAYERS (
        ID VARCHAR PRIMARY KEY,
        NAME VARCHAR,
        ADDRESS VARCHAR,
        CITY VARCHAR,
        STATE_HEADQUARTERED VARCHAR,
        ZIP VARCHAR,
        PHONE VARCHAR,
        AMOUNT_COVERED FLOAT,
        AMOUNT_UNCOVERED FLOAT,
        REVENUE FLOAT,
        COVERED_ENCOUNTERS INT,
        UNCOVERED_ENCOUNTERS INT,
        COVERED_MEDICATIONS INT,
        UNCOVERED_MEDICATIONS INT,
        COVERED_PROCEDURES INT,
        UNCOVERED_PROCEDURES INT,
        COVERED_IMMUNIZATIONS INT,
        UNCOVERED_IMMUNIZATIONS INT,
        UNIQUE_CUSTOMERS INT,
        QOLS_AVG FLOAT,
        MEMBER_MONTHS INT,
        BUSINESS_DATE DATE DEFAULT CURRENT_DATE
    );

    CREATE OR REPLACE TABLE BRONZE.ODS_PROVIDERS (
        ID VARCHAR PRIMARY KEY,
        ORGANIZATION_ID VARCHAR,
        NAME VARCHAR,
        GENDER VARCHAR,
        SPECIALITY VARCHAR,
        ADDRESS VARCHAR,
        CITY VARCHAR,
        STATE VARCHAR,
        ZIP VARCHAR,
        LAT FLOAT,
        LON FLOAT,
        UTILIZATION INT,
        BUSINESS_DATE DATE DEFAULT CURRENT_DATE
    );

    CREATE OR REPLACE TABLE BRONZE.ODS_SUPPLIES (
        "DATE" DATE,
        PATIENT_ID VARCHAR,
        ENCOUNTER_ID VARCHAR,
        CODE VARCHAR,
        DESCRIPTION VARCHAR,
        QUANTITY INT,
        BUSINESS_DATE DATE DEFAULT CURRENT_DATE
    );

    CREATE OR REPLACE TABLE BRONZE.ODS_OBSERVATIONS (
        "DATE" DATE,
        PATIENT_ID VARCHAR,
        ENCOUNTER_ID VARCHAR,
        CODE VARCHAR,
        DESCRIPTION VARCHAR,
        VALUE VARCHAR,
        UNITS VARCHAR,
        TYPE VARCHAR,
        BUSINESS_DATE DATE DEFAULT CURRENT_DATE
    );

    CREATE OR REPLACE TABLE BRONZE.ODS_DEVICES (
        START_DATE DATE,
        STOP_DATE DATE,
        PATIENT_ID VARCHAR,
        ENCOUNTER_ID VARCHAR,
        CODE VARCHAR,
        DESCRIPTION VARCHAR,
        UDI VARCHAR,
        BUSINESS_DATE DATE DEFAULT CURRENT_DATE
    );

    """

    try:
        with engine.connect() as conn:
            for stmt in create_sql.strip().split(";"):
                if stmt.strip():
                    conn.execute(text(stmt.strip()))
            print("✅ All ODS tables created in BRONZE schema.")
    except Exception as e:
        print("❌ Error creating ODS tables in BRONZE schema:", e)
        raise

if __name__ == "__main__":
    create_bronze_ods_tables()